## Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth=100, precision = 2)
print(np.get_printoptions())

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 2, 'suppress': True, 'linewidth': 100, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


## Importing the Data

In [3]:
loan_data = np.genfromtxt("loan-data.csv", delimiter = ';',skip_header =1, autostrip = True)
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
np.isnan(loan_data).sum()

88005

In [5]:
temporary_fill = np.nanmax(loan_data).round(2) + 1
temporary_mean = np.nanmean(loan_data, axis = 0)
temporary_min = np.nanmin(loan_data, axis = 0)

<ipython-input-5-fab7735c1266>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(loan_data, axis = 0)
<ipython-input-5-fab7735c1266>:3: RuntimeWarning: All-NaN slice encountered
  temporary_min = np.nanmin(loan_data, axis = 0)


In [6]:
temporary_fill

68616520.0

In [7]:
temp_stats = np.array([np.nanmax(loan_data,axis=0),temporary_mean,temporary_min])
temp_stats

<ipython-input-7-ea0b8458f7bc>:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmax(loan_data,axis=0),temporary_mean,temporary_min])


array([[68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ]])

In [8]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [9]:
help(np.char.strip)

Help on function strip:

strip(a, chars=None)
    For each element in `a`, return a copy with the leading and
    trailing characters removed.
    
    Calls `str.strip` element-wise.
    
    Parameters
    ----------
    a : array-like of str or unicode
    
    chars : str or unicode, optional
       The `chars` argument is a string specifying the set of
       characters to be removed. If omitted or None, the `chars`
       argument defaults to removing whitespace. The `chars` argument
       is not a prefix or suffix; rather, all combinations of its
       values are stripped.
    
    Returns
    -------
    out : ndarray
        Output array of str or unicode, depending on input type
    
    See Also
    --------
    str.strip
    
    Examples
    --------
    >>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
    >>> c
    array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
    >>> np.char.strip(c)
    array(['aAaAaA', 'aA', 'abBABba'], dtype='<U7')
    >>> np.char.strip(c, 'a

## Splitting the Dataset

### Splitting the Columns

In [10]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [11]:
column_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [12]:
data_clean_str = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header =1, usecols=column_strings, dtype=str)
data_clean_str

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [13]:
data_clean_numeric = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header = 1, usecols=column_numeric,filling_values=temporary_fill)
data_clean_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [14]:
header_full = np.genfromtxt("loan-data.csv", delimiter = ';', skip_footer = loan_data.shape[0], dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [15]:
header_str,header_num = header_full[column_strings],header_full[column_numeric]

In [16]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [17]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [18]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [19]:
checkpoint_1_str = checkpoint("loan_data_chk_str.csv", header_str, data_clean_str )
checkpoint_1_num = checkpoint("loan_data_chk_num.csv", header_num, data_clean_numeric)

In [20]:
checkpoint_1_num['data']

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [21]:
np.array_equal(checkpoint_1_num['data'], data_clean_numeric)

True

## Manipulating String Columns

In [22]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
np.unique(data_clean_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [24]:
header_str[0] = 'issue_date'

### Issue Date

In [25]:
data_clean_str[:,0] = np.char.strip(data_clean_str[:,0],'-15')

In [26]:
np.unique(data_clean_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [27]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [28]:
for i in range(13):
    data_clean_str[:,0] = np.where(data_clean_str[:,0] == months[i],
                                  i,
                                  data_clean_str[:,0])

In [29]:
np.unique(data_clean_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [30]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
data_clean_str[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [32]:
np.unique(data_clean_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [33]:
status_bad = ['','Charged off','Default','Late (31-120 days)']

In [34]:
temp = np.where(np.isin(data_clean_str[:,1],status_bad),0,1)
data_clean_str[:,1] = temp

In [35]:
np.unique(data_clean_str[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [36]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
data_clean_str[:,2]

array([' 36 months', ' 36 months', ' 36 months', ..., ' 36 months', ' 36 months', ' 36 months'],
      dtype='<U69')

In [38]:
np.unique(data_clean_str[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [39]:
data_clean_str[:,2] = np.char.strip(data_clean_str[:,2],' months')

In [40]:
data_clean_str[:,2] = np.where(data_clean_str[:,2] == '',60,data_clean_str[:,2])

In [41]:
np.unique(data_clean_str[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [42]:
np.unique(data_clean_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [43]:
temp = ['','A','B','C','D','E','F','G']
temp_2 = ['','1','2','3','4','5','6','7']

In [44]:
for i in range(8):
    data_clean_str[:,3] = np.where(data_clean_str[:,3] == '0',
                                  '',
                                  data_clean_str[:,3])

#### Filling Sub Grade

In [45]:
for i in np.unique(data_clean_str[:,3])[1:]:
    data_clean_str[:,4] = np.where((data_clean_str[:,4] == '') & (data_clean_str[:,3] == i),
                                      i + '5',
                                      data_clean_str[:,4])

In [46]:
np.unique(data_clean_str[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [47]:
for i in data_clean_str[:,4]:
    data_clean_str[:,4] = np.where(data_clean_str[:,4] == '',
                                  'H1',
                                  data_clean_str[:,4])

#### Removing Grade

In [48]:
data_clean_str = np.delete(data_clean_str,3,axis=1)

In [49]:
data_clean_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [50]:
header_str = np.delete(header_str,3)

In [51]:
header_str

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Converting Sub Grade

In [52]:
keys = list(np.unique(data_clean_str[:,3]))                         
values = list(range(1, np.unique(data_clean_str[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [53]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [54]:
for i in np.unique(data_clean_str[:,3]):
        data_clean_str[:,3] = np.where(data_clean_str[:,3] == i, 
                                          dict_sub_grade[i],
                                          data_clean_str[:,3])

In [55]:
np.unique(data_clean_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [56]:
np.unique(data_clean_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [57]:
temp  = data_clean_str[:,4]
np.unique(temp, return_counts=True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711], dtype=int64))

In [58]:
temp

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [59]:
temp = np.where((temp == '') | (temp=='Not Verified'), 0,1)
np.unique(temp, return_counts=True)

(array([0, 1]), array([3173, 6827], dtype=int64))

In [60]:
data_clean_str[:,4] = temp

In [61]:
data_clean_str[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

### URL

In [62]:
header_str

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [63]:
data_clean_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [64]:
np.char.strip(data_clean_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [65]:
data_clean_str[:,5] = np.char.strip(data_clean_str[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [66]:
data_clean_str[:,5].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [67]:
data_clean_numeric[:,0].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [68]:
np.array_equal(data_clean_str[:,5].astype(dtype=int),data_clean_numeric[:,0].astype(dtype=int))

True

In [69]:
header_str = np.delete(header_str,5)

In [70]:
header_str

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [73]:
data_clean_str[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [74]:
data_clean_str = np.delete(data_clean_str,5,axis=1)

In [75]:
data_clean_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

### State Address

In [78]:
np.unique(data_clean_str[:,5], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [79]:
state_name,state_counts = np.unique(data_clean_str[:,5], return_counts=True)[0],np.unique(data_clean_str[:,5], return_counts=True)[1]

In [84]:
state_counts_sorted = np.argsort(-state_counts)
state_counts_sorted

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20], dtype=int64)

In [86]:
state_name[state_counts_sorted]

array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
       'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
       'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
       'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69')

In [87]:
state_counts[state_counts_sorted]

array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
        216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
         84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
         25,   24,   17,   16,   10], dtype=int64)

In [88]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [94]:
# data_clean_str[:,5] = np.where(np.isin(data_clean_str[:,5],states_west),1,data_clean_str[:,5])
data_clean_str[:,5] = np.where(np.isin(data_clean_str[:,5],states_south),2,data_clean_str[:,5])
data_clean_str[:,5] = np.where(np.isin(data_clean_str[:,5],states_midwest),3,data_clean_str[:,5])
data_clean_str[:,5] = np.where(np.isin(data_clean_str[:,5],states_east),4,data_clean_str[:,5])
data_clean_str[:,5] = np.where(np.isin(data_clean_str[:,5],''),0,data_clean_str[:,5])

In [95]:
np.unique(data_clean_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [98]:
data_clean_str=data_clean_str.astype(dtype=int)

In [99]:
data_clean_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [240]:
checkpoint_2_str=checkpoint('loan-data-checkpt-2-str.csv',header_str,data_clean_str)

In [105]:
checkpoint_2_str[2]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [106]:
data_clean_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [107]:
np.array_equal(data_clean_str,checkpoint_2_str[2])

True

## Manipulating Numeric Columns

In [109]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [110]:
temporary_fill

68616520.0

### Substitute "Filler" Values

#### ID

In [113]:
np.unique(data_clean_numeric[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [116]:
np.isnan(data_clean_numeric).sum()

0

In [128]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [118]:
temp_stats[:,column_numeric]

array([[68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ]])

#### Funded Amount

In [126]:
temp=checkpoint_1_num['data']
np.unique(temp[:,2])

array([    1000.,     1100.,     1175.,     1200.,     1225.,     1325.,     1400.,     1450.,
           1500.,     1600.,     1650.,     1675.,     1725.,     1750.,     1800.,     1875.,
           1900.,     1950.,     2000.,     2100.,     2200.,     2250.,     2300.,     2350.,
           2400.,     2500.,     2525.,     2600.,     2625.,     2650.,     2675.,     2700.,
           2775.,     2800.,     2875.,     2900.,     2950.,     3000.,     3050.,     3075.,
           3100.,     3150.,     3200.,     3225.,     3250.,     3275.,     3300.,     3325.,
           3350.,     3400.,     3450.,     3475.,     3500.,     3525.,     3550.,     3575.,
           3600.,     3650.,     3700.,     3725.,     3750.,     3800.,     3850.,     3875.,
           3900.,     3925.,     3950.,     3975.,     4000.,     4025.,     4100.,     4125.,
           4150.,     4175.,     4200.,     4225.,     4250.,     4275.,     4300.,     4325.,
           4350.,     4375.,     4400.,     4450.,

In [120]:
data_clean_numeric[:,2] = np.where(data_clean_numeric[:,2]==temporary_fill,
                                  temp_stats[2,column_numeric[2]],
                                  data_clean_numeric[:,2])

In [127]:
np.array_equal(data_clean_numeric[:,2],np.unique(temp[:,2]))

False

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [130]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [132]:
for i in [1,3,4,5]:
    data_clean_numeric[:,i] = np.where(data_clean_numeric[:,i]==temporary_fill,
                                      temp_stats[0,column_numeric[i]],
                                      data_clean_numeric[:,i])

In [133]:
data_clean_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [131]:
data_clean_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [137]:
currency_conv = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip=True,usecols=3,skip_header=1)

In [149]:
data_clean_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [150]:
currency_conv

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [154]:
for i in range(1,13):
#     exchange_rate = np.where(exchange_rate == i,
#                              currency_conv[i-1],
#                              exchange_rate)    

    exchange_rate = np.where(exchange_rate == 0,
                            np.mean(currency_conv),
                            exchange_rate)

In [164]:
exchange_rate.shape

(10000, 1)

In [163]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [166]:
data_clean_numeric = np.hstack((data_clean_numeric,exchange_rate))

In [186]:
header_num = np.hstack((header_num,er))

In [215]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

#### From USD to EUR

In [214]:
header_num[column_usd] = [column_i +'_USD' for column_i in header_num[column_usd]]

In [178]:
column_usd = np.array([1,2,4,5])

In [190]:
temp=data_clean_numeric

In [191]:
for i in column_usd:
    temp = np.hstack((temp, np.reshape(temp[:,i] / temp[:,6], (10000,1))))

In [194]:
data_clean_numeric = temp

In [196]:
header_additional

array(['loan_amnt_USD_EUR', 'funded_amnt_USD_EUR', 'installment_USD_EUR', 'total_pymnt_USD_EUR'],
      dtype='<U19')

#### Expanding the header

In [211]:
header_additional = np.array([column_name + '_EUR' for column_name in header_num[column_usd]])

In [212]:
header_num = np.hstack((header_num,header_additional))

In [217]:
header_num = header_num[columns_index_order]

In [218]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [223]:
temp= temp[:,columns_index_order]

In [222]:
temp=data_clean_numeric

In [224]:
temp

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [216]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [225]:
data_clean_numeric = temp

### Interest Rate

In [226]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [232]:
data_clean_numeric[:,5] = temp

In [233]:
data_clean_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [234]:
checkpoint_2_num = checkpoint('loan-data-checkpt_2_num.csv',header_num,data_clean_numeric)

In [237]:
checkpoint_2_num['header'], checkpoint_2_num['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [244]:
loan_data_clean = np.hstack((checkpoint_2_num['data'],checkpoint_2_str['data']))

In [243]:
checkpoint_2_num['data'].shape

(10000, 11)

In [246]:
loan_data_clean.shape

(10000, 17)

In [247]:
header_full = np.concatenate((header_num,header_str))

In [249]:
header_full.size

17

In [255]:
loan_data_clean[2086]

array([373332.  ,   9950.  ,   9038.08,   1000.  ,    908.35,      0.18,    360.97,    327.89,
         1072.82,    974.5 ,      1.1 ,     10.  ,      1.  ,     36.  ,     21.  ,      0.  ,
            1.  ])

## Sorting the New Dataset

In [256]:
loan_data_clean=loan_data_clean[np.argsort(loan_data_clean[:,0])]

In [257]:
loan_data_clean=np.vstack((header_full,loan_data_clean))

In [258]:
loan_data_clean

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

## Storing the New Dataset

In [261]:
loan_data_pp = np.savetxt("loan-data-preprocessed.csv",loan_data_clean, fmt='%s',delimiter=',')